Algoritmo "Área_do_trapézio "
// Descrição   :Cálculo da area do trapezio
// Autor(a)    : Diogo Dias
// Data atual  : 21/09/2017
Var
  basemaior,basemenor,altura,area:real
Inicio
escreva("Qual a base maior?")
leia(Basemaior)
escreva("Qual a base menor?")
leia(basemenor)
escreva("Qual a altura?")
leia(altura)
area<-basemaior+basemenor*altura/2
escreva("A área  é", area)

Fimalgoritmo